// tokens.h
// ~~~~~~~~
// Token macro definitions.
#ifndef TOKEN
#define TOKEN(X)
#endif

#ifndef OPERATOR
#define OPERATOR(X, CHAR) TOKEN(X)
#endif

#ifndef PUNCTUATOR
#define PUNCTUATOR(X, CHAR) TOKEN(X)
#endif

#ifndef KEYWORD
#define KEYWORD(X) TOKEN(KW_##X)
#endif

TOKEN(ID)
TOKEN(NUM_LIT)
TOKEN(CHAR_LIT)
TOKEN(STR_LIT)
TOKEN(BHCC_EOF)
TOKEN(UNKNOWN)

OPERATOR(ADD, "+")
OPERATOR(SUB, "-")
OPERATOR(STAR, "*")
OPERATOR(DIV, "/")
OPERATOR(MODULO, "%")
OPERATOR(INCREMENT, "++")
OPERATOR(DECREMENT, "--")
OPERATOR(ASSIGN, "=")
OPERATOR(ADD_ASSIGN, "+=")
OPERATOR(SUB_ASSIGN, "-=")
OPERATOR(MUL_ASSIGN, "*=")
OPERATOR(DIV_ASSIGN, "/=")
OPERATOR(MOD_ASSIGN, "%=")
OPERATOR(EQ, "==")
OPERATOR(GE, ">")
OPERATOR(LE, "<")
OPERATOR(NE, "!=")
OPERATOR(GEQ, ">=")
OPERATOR(LEQ, "<=")
OPERATOR(LOG_AND, "&&")
OPERATOR(LOG_OR, "||")
OPERATOR(LOG_NOT, "!")
OPERATOR(BIT_AND, "&")
OPERATOR(BIT_OR, "|")
OPERATOR(BIT_ASSIGN_XOR, "^=")
OPERATOR(BIT_ASSIGN_AND, "&=")
OPERATOR(BIT_ASSIGN_OR, "|=")
OPERATOR(BIT_XOR, "^")
OPERATOR(BIT_COMP, "~")
OPERATOR(SHL, "<<")
OPERATOR(SHR, ">>")
OPERATOR(SHL_ASSIGN, "<<=")
OPERATOR(SHR_ASSIGN, ">>=")
OPERATOR(COMMA, ",")
OPERATOR(DOT, ".")
OPERATOR(ARROW, "->")
OPERATOR(ADDRESS, "&")

PUNCTUATOR(OPEN_BRACE, "{")
PUNCTUATOR(CLOSE_BRACE, "}")
PUNCTUATOR(OPEN_PAREN, "(")
PUNCTUATOR(CLOSE_PAREN, ")")
PUNCTUATOR(OPEN_BRACKET, "[")
PUNCTUATOR(CLOSE_BRACKET, "]")
PUNCTUATOR(VARIADIC, "...")
PUNCTUATOR(SEMI_COLON, ";")
PUNCTUATOR(SINGLE_QUOTE, "'")
PUNCTUATOR(DOUBLE_QUOTE, "\"")
PUNCTUATOR(INLINE_COMMENT, "//")
PUNCTUATOR(BLOCK_COMMENT, "/*")

KEYWORD(break)
KEYWORD(case)
KEYWORD(char)
KEYWORD(const)
KEYWORD(continue)
KEYWORD(default)
KEYWORD(do)
KEYWORD(double)
KEYWORD(else)
KEYWORD(enum)
KEYWORD(extern)
KEYWORD(float)
KEYWORD(for)
KEYWORD(goto)
KEYWORD(if)
KEYWORD(int)
KEYWORD(long)
KEYWORD(register)
KEYWORD(return)
KEYWORD(short)
KEYWORD(signed)
KEYWORD(sizeof)
KEYWORD(static)
KEYWORD(struct)
KEYWORD(switch)
KEYWORD(typedef)
KEYWORD(union)
KEYWORD(unsigned)
KEYWORD(void)
KEYWORD(volatile)
KEYWORD(while)
#define KW_COUNT 31
#define MAX_KW_LEN 8

#undef TOKEN
#undef OPERATOR
#undef PUNCTUATOR
#undef KEYWORD
